using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stage.Core
{
    // From ImGui
    public enum TypedCode
    {
        None = 0,
        Tab = 512,
        LeftArrow,
        RightArrow,
        UpArrow,
        DownArrow,
        PageUp,
        PageDown,
        Home,
        End,
        Insert,
        Delete,
        Backspace,
        Space,
        Enter,
        Escape,
        LeftCtrl, LeftShift, LeftAlt, LeftSuper,
        RightCtrl, RightShift, RightAlt, RightSuper,
        Menu,
        Key0, Key1, Key2, Key3, Key4, Key5, Key6, Key7, Key8, Key9,
        A, B, C, D, E, F, G, H, I, J,
        K, L, M, N, O, P, Q, R, S, T,
        U, V, W, X, Y, Z,
        F1, F2, F3, F4, F5, F6,
        F7, F8, F9, F10, F11, F12,
        Apostrophe,        
        Comma,             
        Minus,             
        Period,            
        Slash,             
        Semicolon,         
        Equal,             
        LeftBracket,       
        Backslash,
        RightBracket,      
        GraveAccent,       
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        Keypad0, Keypad1, Keypad2, Keypad3, Keypad4,
        Keypad5, Keypad6, Keypad7, Keypad8, Keypad9,
        KeypadDecimal,
        KeypadDivide,
        KeypadMultiply,
        KeypadSubtract,
        KeypadAdd,
        KeypadEnter,
        KeypadEqual,

        GamepadStart,          
        GamepadBack,           
        GamepadFaceLeft,       
        GamepadFaceRight,      
        GamepadFaceUp,         
        GamepadFaceDown,       
        GamepadDpadLeft,       
        GamepadDpadRight,      
        GamepadDpadUp,         
        GamepadDpadDown,       
        GamepadL1,             
        GamepadR1,             
        GamepadL2,             
        GamepadR2,             
        GamepadL3,             
        GamepadR3,             
        GamepadLStickLeft,     
        GamepadLStickRight,    
        GamepadLStickUp,       
        GamepadLStickDown,     
        GamepadRStickLeft,     
        GamepadRStickRight,    
        GamepadRStickUp,       
        GamepadRStickDown,     

        MouseLeft, MouseRight, MouseMiddle, MouseX1, MouseX2, MouseWheelX, MouseWheelY,

        CtrlMod = 1 << 12,
        ShiftMod = 1 << 13,
        AltMod = 1 << 14,
        SuperMod = 1 << 15,
        ShortcutMod = 1 << 11,
    }
}
